import { IBrokerages } from "../interfaces/brokerages";
import { IBusinessPartners } from "../interfaces/business-partners";
import { IItens } from "../interfaces/itens";
import { IPaymentType } from "../interfaces/payment-type";
import { IPersons } from "../interfaces/persons";
import { IPolicy } from "../interfaces/policy";

export class Policy implements IPolicy {
  numeroProcessoInterno!: string;
  nossoNumero!: string;
  tipoEmissao!: "EndossoMovimentoSemIof" | "EndossoMovimentoComIof" | "ApoliceAberta" | "EndossoRestituicaoComCancelamento" | "ApoliceSemIof" | "EndossoSemMovimento" | "CancelamentoApoliceSemRestituicao" | "ApoliceComIof";
  tipoCotador!: "V";
  valorPremioTotal!: number;
  valorIof!: number;
  valorImportanciaSegurada!: number;
  valorPremioLiquido!: number;
  codigoRamo!: string;
  numeroApolice!: number;
  ehRenovacao!: boolean;
  usuario!: "root";
  dataHoraDigitacao!: string;
  dataInicioVigencia!: string;
  dataFimVigencia!: string;
  dataInicioViagem!: string;
  filial!: number;
  codigoProduto!: number;
  executivoDeConta!: number;
  itens!: IItens[];
  textoEndosso?: string | undefined;
  formaPagamento!: IPaymentType;
  corretagens!: IBrokerages[];
  cosseguradoras!: string;
  parceirosNegocio!: IBusinessPartners[];
  pessoas!: IPersons[];
  copiarDadosSeguradoBPEndosso!: boolean;
  impressaoBoletoFisico!: "NaoImprime";
  ehTransporte!: boolean;
  valorCambioMoedaEstrangeira!: number;
  prorrogacaoDeVigencia!: boolean;
  ajusteComercial!: number;
  lmiUnico!: boolean;
  subvencoes?: string | undefined;
  tipoResseguro!: "SemInformacao";
  codigoCobrancaUnificada!: number;
  emissaoHistorico?: boolean | undefined;
  emissaoPedIndice?: boolean | undefined;
  dataRecebimentoCia!: string;
  codigoCIA!: number;
}