const XmlTags = {
  numeroProcessoInterno: 'NumeroDoProcessoInterno',
  nossoNumero: 'NossoNumero',
  tipoEmissao: 'TipoEmissao',
  tipoCotador: 'TipoCotador',
  valorPremioTotal: 'ValorPremioTotal',
  valorIof: 'ValorIof',
  valorImportanciaSegurada: 'ValorImportanciaSegurada',
  valorPremioLiquido: 'ValorPremioLiquido',
  codigoRamo: 'CodigoRamo',
  numeroApolice: 'numeroApolice',
  ehRenovacao: 'EhRenovacao',
  usuario: 'Usuario',
  dataHoraDigitacao: 'DataHoraDigitacao',
  dataInicioVigencia: 'DataInicioVigencia',
  dataFimVigencia: 'DataFimVigencia',
  dataInicioViagem: 'DataInicioViagem',
  filial: 'Filial',
  codigoProduto: 'CodigoProduto',
  executivoDeConta: 'ExecutivoDeConta',
  itens: 'Itens',
  item: 'Item',
  codigo: 'Codigo',
  coberturas: 'Coberturas',
  cobertura: 'Cobertura',
  ehAssistencia: 'EhAssistencia',
  valorPremio: 'ValorPremio',
  clausulas: 'Clausulas',
  locais: 'Locais',
  localRisco: 'LocalRisco',
  bairro: 'Bairro',
  cep: 'CEP',
  cidade: 'Cidade',
  complemento: 'Complemento',
  logradouro: 'Logradouro',
  tipoLogradouro: 'TipoLogradouro',
  uf: 'UF',
  textoEndosso: 'TextoEndosso',
  formaPagamento: 'FormaPagamento',
  adicionaisFracionamento: 'AdicionaisFracionamento',
  numeroBoleto: 'NumeroBoleto',
  tipo: 'Tipo',
  corretagens: 'Corretagens',
  corretagem: 'Corretagem',
  codigoCorretor: 'CodigoCorretor',
  corretorPrincipal: 'CorretorPrincipal',
  percentualCorretagem: 'PercentualCorretagem',
  cosseguradoras: 'Cosseguradoras',
  parceirosNegocio: 'ParceirosNegocio',
  parceiroNegocio: 'ParceiroNegocio',
  agenciamento: 'Agenciamento',
  codigoCanal: 'CodigoCanal',
  percentual: 'Percentual',
  quantidadeParcelas: 'QuantidadeParcelas',
  tipoCanal: 'TipoCanal',
  pessoas: 'Pessoas',
  pessoa: 'Pessoa',
  nome: 'Nome',
  nomeAbreviado: 'NomeAbreviado',
  nomeContato: 'NomeContato',
  tipoProponente: 'TipoProponente',
  tipoPessoa: 'TipoPessoa',
  cpf: 'Cpf',
  cnpj: 'Cnpj',
  renda: 'Renda',
  profissao: 'Profissao',
  emailContato: 'EmailContato',
  tipoDocumento: 'TipoDocumento',
  numeroDocumento: 'NumeroDocumento',
  orgaoExpedidor: 'OrgaoExpedidor',
  dataExpedicao: 'DataExpedicao',
  dataNascimento: 'DataNascimento',
  ramoAtividadeEmpresa: 'RamoAtividadeEmpresa',
  sexo: 'Sexo',
  telefones: 'Telefones',
  telefone: 'Telefone',
  ddd: 'DDD',
  numero: 'Numero',
  observacao: 'Observacao',
  ramal: 'Ramal',
  enderecos: 'Enderecos',
  endereco: 'Endereco',
  tipoEndereco: 'TipoEndereco',
  codigoCNAE: 'CodigoCNAE',
  ehResponsavel: 'EhResponsavel',
  grupoFinanceiro: 'GrupoFinanceiro',
  codigoRamoAtividade: 'CodigoRamoAtividade',
  copiarDadosSeguradoBPEndosso: 'CopiarDadosSeguradoBPEndosso',
  impressaoBoletoFisico: 'ImpressaoBoletoFisico',
  ehTransporte: 'EhTransporte',
  valorCambioMoedaEstrangeira: 'ValorCambioMoedaEstrangeira',
  prorrogacaoDeVigencia: 'ProrrogacaoDeVigencia',
  ajusteComercial: 'AjusteComercial',
  lmiUnico: 'LmiUnico',
  subvencoes: 'Subvencoes',
  tipoResseguro: 'TipoResseguro',
  codigoCobrancaUnificada: 'CodigoCobrancaUnificada',
  emissaoHistorico: 'EmissaoHistorico',
  emissaoPedIndice: 'EmissaoPedIndice',
  dataRecebimentoCia: 'DataRecebimentoCia',
  codigoCIA: 'CodigoCIA'
};

const XmlDefaultNilTags = [
  XmlTags.clausulas,
  XmlTags.textoEndosso,
  XmlTags.adicionaisFracionamento,
  XmlTags.agenciamento,
  XmlTags.nomeContato,
  XmlTags.profissao,
  XmlTags.numeroDocumento,
  XmlTags.orgaoExpedidor,
  XmlTags.dataExpedicao,
  XmlTags.observacao,
  XmlTags.grupoFinanceiro,
  XmlTags.subvencoes,
  XmlTags.emissaoHistorico,
  XmlTags.emissaoPedIndice
];

export {
  XmlTags,
  XmlDefaultNilTags
};